/* tslint:disable */
/* eslint-disable */
/**
 * Swinging Example API
 * Kuy Hee Kuy Hee
 *
 * The version of the OpenAPI document: 2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

