definitions:
  dtos.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  dtos.LoginResponse:
    properties:
      email:
        type: string
      token:
        type: string
      username:
        type: string
    type: object
  dtos.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: Kuy Hee Kuy Hee
  title: Swinging Example API
  version: "2.5"
paths:
  /auth/login:
    post:
      description: Login
      parameters:
      - description: LoginRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.LoginRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.LoginResponse'
      summary: Login
  /auth/register:
    post:
      description: Register
      parameters:
      - description: RegisterRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.RegisterRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.LoginResponse'
      summary: Register
swagger: "2.0"
